apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "kubenews#123456"
            - name: POSTGRES_USER
              value: "kubenews"
            - name: POSTGRES_DB
              value: "kubenewsBD"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubenews-web
  template:
    metadata:
      labels:
        app: kubenews-web
    spec:
      containers:
      - name: kubenews-web
        image: edsonrodrigoba/kube-news:v2
        env:
        - name: DB_DATABASE
          value:  "kubenewsBD"
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD
          value: "kubenews#123456" 
        - name: DB_HOST
          value: "postgre"

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubenews-web
spec:
  selector:
    app: kubenews-web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30252
  type: NodePort